language: c++
dist: trusty
sudo: false
os:
  - linux
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake-data
      - cmake




matrix:

  exclude:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc

  include:
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost1.55-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9 && CTEST_OUTPUT_ON_FAILURE=1"

    - os: linux
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost1.55-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && CTEST_OUTPUT_ON_FAILURE=1"

    - os: linux
      compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost1.55-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && CTEST_OUTPUT_ON_FAILURE=1"

    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost1.55-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && CTEST_OUTPUT_ON_FAILURE=1"

    - os: linux
      compiler: clang-3.9
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libboost1.55-all-dev
      env:
         - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9 && CTEST_OUTPUT_ON_FAILURE=1"

    - os: linux
      compiler: clang-4.0
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libboost1.55-all-dev
      env:
         - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && CTEST_OUTPUT_ON_FAILURE=1"

    - os: linux
      compiler: clang-5.0
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost1.55-all-dev
      env:
         - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && CTEST_OUTPUT_ON_FAILURE=1"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - pip install --user xmlrunner
  - pip install --user pygraphviz

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make VERBOSE=1
  - python3 ../test/cmd_line/test.py test-reports ../include_gardener.conf  include_gardener ../test/test_files
  - make test
