language: c++
dist: trusty
sudo: false
os:
  - linux
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake-data
      - cmake




matrix:

  exclude:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc

  include:
    - os: linux
      COMPILER=g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost1.55-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - JOB="gcc-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost1.55-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
         - JOB="gcc-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost1.55-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
         - JOB="gcc-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost1.55-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
         - JOB="gcc-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libboost1.55-all-dev
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
         - JOB="clang-3.9"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libboost1.55-all-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
         - JOB="clang-4.0"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost1.55-all-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
         - JOB="clang-5.0"

before_install:
    - eval "${MATRIX_EVAL}"


before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make VERBOSE=1
